; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define ProjectDir SourcePath


#define MyAppName "Filefinder"
#define MyAppVersion "1.0"
#define MyAppPublisher "The author"
#define MyAppURL "https://sites.google.com/"
#define MyAppExeName "Filefinder.exe"



[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4D1A530E-9AB8-41F6-9B33-B4A6C3F637AE}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=license.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=Filefinder-v.1.0
SolidCompression=yes
WizardStyle=modern
SetupIconFile=resources\icon.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "arabic"; MessagesFile: "compiler:Languages\Arabic.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startup"; Description: "Run Filefinder automatically when Windows starts"; GroupDescription: "Additional options:"; Flags: checkedonce


[Registry]
; FIXED: this previously had no "Tasks:" clause, so it was written
; unconditionally regardless of whether the "startup" checkbox above
; was ticked - every install silently got an autostart entry. Now it
; only applies when that task is selected, and is removed again on
; uninstall (uninsdeletevalue).
;
; /tray tells main.py to stay in the system tray only and not open the
; main window (see main.py's _wants_tray_start()). Repeated launches -
; including from the "Open with File Finder" context menu below - now
; detect the already-running instance and forward their request to it
; instead of starting a second process/tray icon (see
; app/single_instance.py), so this is safe to launch on every boot.
Root: HKLM; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "Filefinder"; ValueData: """{app}\Filefinder.exe"" /tray"; Flags: uninsdeletevalue; Tasks: startup

; Right-click ON a folder itself.
Root: HKCR; Subkey: "Directory\shell\FileFinder"; ValueType: string; ValueName: ""; ValueData: "Open with File Finder"; Flags: uninsdeletekey
Root: HKCR; Subkey: "Directory\shell\FileFinder"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\FileFinder.exe"""
Root: HKCR; Subkey: "Directory\shell\FileFinder\command"; ValueType: string; ValueName: ""; ValueData: """{app}\FileFinder.exe"" ""%1"""

; Right-click the empty background INSIDE a folder (search that folder
; without needing to right-click a specific subfolder). %V expands to
; the folder currently open in Explorer. Optional - delete this whole
; block if you only want the entry when right-clicking a folder itself.
Root: HKCR; Subkey: "Directory\Background\shell\FileFinder"; ValueType: string; ValueName: ""; ValueData: "Open with File Finder"; Flags: uninsdeletekey
Root: HKCR; Subkey: "Directory\Background\shell\FileFinder"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\FileFinder.exe"""
Root: HKCR; Subkey: "Directory\Background\shell\FileFinder\command"; ValueType: string; ValueName: ""; ValueData: """{app}\FileFinder.exe"" ""%V"""


[Files]
; NOTE: this "_internal" subfolder layout is what PyInstaller 6.x
; produces in --onedir mode (which is what Filefinder.bat builds,
; since it doesn't pass --onefile). PyInstaller 6.x's Windows 7 support
; is uncertain - the project's own build_exe.bat pins the older
; PyInstaller 4.10 specifically for Windows 7 32-bit compatibility. If
; the built app doesn't run on your Windows 7 32-bit target machine,
; that mismatch is the first thing to check - either pin PyInstaller to
; an older release for this build too, or confirm your installed
; PyInstaller 6.x build genuinely still runs on Windows 7 32-bit.
;Source: "{#ProjectDir}dist\Filefinder\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#ProjectDir}\dist\Filefinder\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
; [Files]
Source: "{#ProjectDir}dist\Filefinder\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjectDir}dist\Filefinder\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs


[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
